### ISSUE TITLE
Server down

### ISSUE THREAD

**Issue by rugk** [UploadMe/UploadMe#13]
![uploadmedown](https://cloud.githubusercontent.com/assets/11966684/9563972/9c0b35a2-4e96-11e5-8f5e-8da8bf96064a.PNG)

**Comment by Carlgo11** [comment]
yup. Currently waiting for some hosting companies to respond to us. Hopefully one of them can host the site.

**Comment by Polarcraft** [comment]
Carl private message me ;)

**Comment by Polarcraft** [comment]
This issue was fixed when we put uploadme onto a new service.
